# Generated by Django 5.2.17 on 2026-08-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre y apellido')),
                ('cedula', models.CharField(max_length=20, verbose_name='cedula')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
