# Generated by Django 5.2.17 on 2026-08-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='cedula',
            field=models.CharField(max_length=20, verbose_name='cédula'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='teléfono'),
        ),
    ]
